Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/app.handler
      Runtime: nodejs20.x
      CodeUri: hello-world/
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get
